name: worknetwork
description: WorkNetwork a community of professionals networking, sharing &
  learning together.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.2.7+45

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  appsflyer_sdk: ^6.5.2+2
  auto_route: ^4.2.0
  cached_network_image: ^3.2.0
  chewie: ^1.3.4
  chopper: ^4.0.6
  cupertino_icons: ^1.0.5
  custom_rounded_rectangle_border: ^0.2.0-nullsafety.0
  dartz: ^0.10.1
  internet_connection_checker: ^0.0.1+4
  device_info: ^2.0.3
  equatable: ^2.0.3
  firebase_core: ^1.10.0
  firebase_dynamic_links: ^4.3.1
  flutter_hooks: ^0.18.5+1
  flutter_html: ^3.0.0-alpha.5
  flutter_segment: ^3.9.0
  flutter_sticky_header: ^0.6.3
  flutter_svg: ^1.1.1+1
  fluttertoast: ^8.0.9
  freezed_annotation: ^2.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^1.0.4
  http: ^0.13.4
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  json_annotation: ^4.5.0
  libphonenumber: ^2.0.2
  lint: ^1.8.2
  lottie: ^1.3.0
  metadata_fetch: ^0.4.1
  onesignal_flutter: ^3.3.2
  package_info_plus: ^1.4.3+1
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  phone_number: ^0.12.0+2
  sentry_flutter: ^6.6.2
  share_plus: ^4.0.10
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.4
  uuid: ^3.0.6
  video_player: ^2.4.5
  bordered_text: ^2.0.0
  dyte_client: ^0.8.1
  timeago: ^3.2.2
  flutter_staggered_grid_view: ^0.6.1
  carousel_slider: ^4.1.1
  webview_flutter: ^3.0.4
  cloud_firestore: ^3.2.1
  date_time_picker: ^2.1.0
  socket_io_client: ^2.0.0
  neopop: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^4.2.0
  build_runner: ^2.1.11
  change_app_package_name: ^1.1.0
  chopper_generator: ^4.0.6
  freezed: ^2.0.3+1
  hive_generator: ^1.1.3
  json_serializable: ^6.1.6
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/splash/
    - assets/images/coming_soon/
    - assets/lottie/
    - assets/svg/
    - assets/icons/
    - assets/video/
    - lang/en.json
    - config/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: WorkNetIcons
      fonts:
        - asset: assets/icons/WorkNetIcons.ttf
    - family: Roobert
      fonts:
        - asset: assets/fonts/Roobert/Roobert-Light.otf
          weight: 300
        - asset: assets/fonts/Roobert/Roobert-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/Roobert/Roobert-Regular.otf
          weight: 400
        - asset: assets/fonts/Roobert/Roobert-RegularItalic.otf
          style: italic
          weight: 400
        - asset: assets/fonts/Roobert/Roobert-Medium.otf
          weight: 500
        - asset: assets/fonts/Roobert/Roobert-MediumItalic.otf
          style: italic
          weight: 500
        - asset: assets/fonts/Roobert/Roobert-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Roobert/Roobert-SemiBoldItalic.otf
          style: italic
          weight: 600
        - asset: assets/fonts/Roobert/Roobert-Bold.otf
          weight: 700
        - asset: assets/fonts/Roobert/Roobert-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/Roobert/Roobert-Heavy.otf
          weight: 900
        - asset: assets/fonts/Roobert/Roobert-HeavyItalic.otf
          style: italic
          weight: 900
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit/Outfit-Thin.ttf
          weight: 100
        - asset: assets/fonts/Outfit/Outfit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Outfit/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Outfit/Outfit-Black.ttf
          weight: 900
    - family: Aeonik
      fonts:
        - asset: assets/fonts/Aeonik-Air.ttf
          weight: 100
        - asset: assets/fonts/Aeonik-AirItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Aeonik-Thin.ttf
          weight: 200
        - asset: assets/fonts/Aeonik-ThinItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Aeonik-Light.ttf
          weight: 300
        - asset: assets/fonts/Aeonik-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Aeonik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Aeonik-RegularItalic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Aeonik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Aeonik-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Aeonik-Bold.ttf
          weight: 600
        - asset: assets/fonts/Aeonik-BoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Aeonik-Black.ttf
          weight: 700
        - asset: assets/fonts/Aeonik-BlackItalic.ttf
          style: italic
          weight: 700
    - family: Apercu
      fonts:
        - asset: assets/fonts/Apercu/Apercu Light.otf
          weight: 200
        - asset: assets/fonts/Apercu/Apercu Light Italic.otf
          style: italic
          weight: 200
        - asset: assets/fonts/Apercu/Apercu Regular.otf
          weight: 400
        - asset: assets/fonts/Apercu/Apercu Medium.otf
          weight: 500
        - asset: assets/fonts/Apercu/Apercu Medium Italic.otf
          style: italic
          weight: 500
        - asset: assets/fonts/Apercu/Apercu Bold.otf
          weight: 700
        - asset: assets/fonts/Apercu/Apercu Bold Italic.otf
          style: italic
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
