name: worknetwork
description: WorkNetwork a community of professionals networking, sharing &
  learning together.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.9.8+34

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  agora_rtc_engine: ^4.0.7
  animated_text_kit: ^4.2.1
  appsflyer_sdk: ^6.3.5+3
  auto_route: ^2.2.0
  bloc: ^7.0.0
  cached_network_image: ^3.1.0
  chewie: ^1.2.2
  chopper: ^4.0.1
  cupertino_icons: ^1.0.3
  custom_rounded_rectangle_border: ^0.2.0-nullsafety.0
  dartz: ^0.10.0
  internet_connection_checker: ^0.0.1+2
  device_info: ^2.0.2
  equatable: ^2.0.3
  firebase_dynamic_links: ^2.0.7
  flutter_bloc: ^7.0.1
  flutter_custom_tabs: ^0.7.0
  flutter_facebook_auth: ^3.5.0
  flutter_hooks: ^0.17.0
  flutter_html: ^2.1.0
  flutter_segment: ^3.1.2
  # flutter_statusbarcolor: ^0.2.3
  flutter_sticky_header: ^0.6.0
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.7
  freezed_annotation: ^0.14.2
  google_sign_in: ^5.0.5
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hooks_riverpod: ^0.14.0+4
  http: ^0.13.3
  image_picker: ^0.8.3+3
  intl: ^0.17.0
  json_annotation: ^4.0.1
  kiwi: ^3.0.0
  libphonenumber: ^2.0.2
  lint: ^1.5.3
  lottie: ^1.1.0
  metadata_fetch: ^0.4.1
  onesignal_flutter: ^3.2.3
  package_info: ^2.0.2
  path_provider: ^2.0.2
  permission_handler: ^8.1.6
  phone_number: ^0.12.0+1
  sentry: ^5.1.0
  share: ^2.0.4
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  sign_in_with_apple: ^3.1.0
  url_launcher: ^6.0.9
  uuid: ^3.0.4
  video_player: ^2.2.3
  web_socket_channel: ^2.1.0
  intercom_flutter: ^5.0.0
  linkedin_login: ^2.0.1
  bordered_text: ^2.0.0
  dyte_client: ^0.1.1
  timeago: ^3.1.0
  flutter_staggered_grid_view: ^0.4.0
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.1.0
  build_runner: ^2.0.6
  change_app_package_name: ^1.0.0
  chopper_generator: ^4.0.1
  freezed: ^0.14.2
  hive_generator: ^1.1.0
  json_serializable: ^4.1.4
  kiwi_generator: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/splash/
    - assets/images/coming_soon/
    - assets/lottie/
    - assets/svg/
    - assets/icons/
    - assets/video/
    - lang/en.json
    - config/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: WorkNetIcons
      fonts:
        - asset: assets/icons/WorkNetIcons.ttf
    - family: Aeonik
      fonts:
        - asset: assets/fonts/Aeonik-Air.ttf
          weight: 100
        - asset: assets/fonts/Aeonik-AirItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Aeonik-Thin.ttf
          weight: 200
        - asset: assets/fonts/Aeonik-ThinItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Aeonik-Light.ttf
          weight: 300
        - asset: assets/fonts/Aeonik-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Aeonik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Aeonik-RegularItalic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Aeonik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Aeonik-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Aeonik-Bold.ttf
          weight: 600
        - asset: assets/fonts/Aeonik-BoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Aeonik-Black.ttf
          weight: 700
        - asset: assets/fonts/Aeonik-BlackItalic.ttf
          style: italic
          weight: 700
    - family: Apercu
      fonts:
        - asset: assets/fonts/Apercu/Apercu Light.otf
          weight: 200
        - asset: assets/fonts/Apercu/Apercu Light Italic.otf
          style: italic
          weight: 200
        - asset: assets/fonts/Apercu/Apercu Regular.otf
          weight: 400
        - asset: assets/fonts/Apercu/Apercu Medium.otf
          weight: 500
        - asset: assets/fonts/Apercu/Apercu Medium Italic.otf
          style: italic
          weight: 500
        - asset: assets/fonts/Apercu/Apercu Bold.otf
          weight: 700
        - asset: assets/fonts/Apercu/Apercu Bold Italic.otf
          style: italic
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
