name: worknetwork
description: WorkNetwork a community of professionals networking, sharing &
  learning together.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.8.7+16

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^0.6.7
  bloc: ^6.1.0
  cached_network_image: ^2.2.0+1
  chewie: ^0.9.10
  chopper: ^3.0.2
  cupertino_icons: ^0.1.3
  dartz: ^0.9.1
  data_connection_checker: ^0.3.4
  device_info: ^0.4.2+8
  equatable: ^1.2.5
  firebase_dynamic_links: ^0.6.0
  flutter_bloc: ^6.0.0
  flutter_custom_tabs: ^0.6.0
  flutter_facebook_login: ^3.0.0
  flutter_hooks: ^0.15.0
  flutter_html: ^1.0.2
  flutter_linkedin: ^1.0.2
  flutter_segment: ^3.0.0
  flutter_statusbarcolor: ^0.2.3
  flutter_svg: ^0.18.0
  fluttertoast: ^7.1.1
  freezed_annotation: ^0.12.0
  google_sign_in: ^4.5.1
  hive: ^1.4.3
  hive_flutter: ^0.3.1
  hooks_riverpod: ^0.12.1
  http: ^0.12.1
  image_picker: ^0.6.7+4
  intl: ^0.16.1
  json_annotation: ^3.0.1
  kiwi: ^2.0.0
  libphonenumber: ^1.0.1
  lint: ^1.2.0
  lottie: ^0.5.1
  metadata_fetch: ^0.3.3
  onesignal_flutter: ^2.6.1
  package_info: ^0.4.3
  path_provider: ^1.6.14
  phone_number: ^0.6.2+4
  sentry: ">=3.0.0 <4.0.0"
  shared_preferences: ^0.5.8
  shimmer: ^1.1.1
  sign_in_with_apple: ^2.5.2
  url_launcher: ^5.5.0
  video_player: ^0.10.12
  web_socket_channel: ^1.1.0
  share: ^0.6.5+4
  agora_rtc_engine: ^3.1.2
  permission_handler: ^3.0.0
  uuid: ^2.2.2
  animated_text_kit: ^3.1.2
  custom_rounded_rectangle_border: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.8
  build_runner: ^1.10.0
  change_app_package_name: ^0.1.2
  chopper_generator: ^3.0.4
  hive_generator: ^0.8.0
  json_serializable: ^3.3.0
  kiwi_generator: ^2.0.0
  freezed: ^0.12.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lottie/
    - assets/svg/
    - assets/icons/
    - lang/en.json
    - config/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: WorkNetIcons
      fonts:
        - asset: assets/icons/WorkNetIcons.ttf
    - family: Aeonik
      fonts:
        - asset: assets/fonts/Aeonik-Air.ttf
          weight: 100
        - asset: assets/fonts/Aeonik-AirItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Aeonik-Thin.ttf
          weight: 200
        - asset: assets/fonts/Aeonik-ThinItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Aeonik-Light.ttf
          weight: 300
        - asset: assets/fonts/Aeonik-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Aeonik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Aeonik-RegularItalic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Aeonik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Aeonik-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Aeonik-Bold.ttf
          weight: 600
        - asset: assets/fonts/Aeonik-BoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Aeonik-Black.ttf
          weight: 700
        - asset: assets/fonts/Aeonik-BlackItalic.ttf
          style: italic
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
