/// Flutter icons WorkNetIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WorkNetIcons
///      fonts:
///       - asset: fonts/WorkNetIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class WorkNetIcons {
  WorkNetIcons._();

  static const _kFontFam = 'WorkNetIcons';

  static const IconData articles = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData comment = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData community = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData delete = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData doublecheck = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData filters = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData inbox = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData like = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData menu = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData message = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData newPost = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData notification = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData people = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData send = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData videos = IconData(0xe80e, fontFamily: _kFontFam);
}
