// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD6tI44P6FYLd6WTX-0Ib2oRBRjNTfg7o',
    appId: '1:180973412253:android:f5012124ff1b418a4b1974',
    messagingSenderId: '180973412253',
    projectId: 'crater-b6a7b',
    storageBucket: 'crater-b6a7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATRBYdNb_4BKa7eRTtTz8jBeKQKfW06K4',
    appId: '1:180973412253:ios:2ffa233fab0624324b1974',
    messagingSenderId: '180973412253',
    projectId: 'crater-b6a7b',
    storageBucket: 'crater-b6a7b.appspot.com',
    iosClientId: '180973412253-gji1esk3n4dj01al814cidfqg4q44nu0.apps.googleusercontent.com',
    iosBundleId: 'com.wurknet.mobile',
  );
}
